# Generated by Django 5.1.6 on 2025-02-19 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state__name', 'name'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('alias', models.CharField(max_length=255, verbose_name='Sigla')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('sponsor', models.CharField(max_length=255, verbose_name='Responsável')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.city', verbose_name='Município')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
