# Generated by Django 5.1.6 on 2025-02-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0002_alter_city_options_alter_state_options_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
    ]
