# Generated by Django 5.1.6 on 2025-02-21 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0004_company_state_alter_company_city_unit_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.state', verbose_name='Estado'),
        ),
    ]
