# Generated by Django 5.1.6 on 2025-02-21 16:58

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0006_unit_state_alter_unit_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='sector_parent',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='company', chained_model_field='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='sisponto.sector', verbose_name='Setor Pai'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='unit',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='company', chained_model_field='company', on_delete=django.db.models.deletion.CASCADE, to='sisponto.unit', verbose_name='Unidade'),
        ),
    ]
