# Generated by Django 5.1.6 on 2025-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0007_alter_sector_sector_parent_alter_sector_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla'),
        ),
    ]
