# Generated by Django 5.1.6 on 2025-02-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0008_sector_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.state', verbose_name='Estado'),
        ),
    ]
