# Generated by Django 5.1.6 on 2025-02-22 11:14

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisponto', '0009_alter_unit_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=11, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('zip_code', models.CharField(max_length=8, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('city', smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='sisponto.city', verbose_name='Município')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.state', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.company', verbose_name='Empresa')),
                ('sector', smart_selects.db_fields.ChainedForeignKey(chained_field='unit', chained_model_field='unit', on_delete=django.db.models.deletion.CASCADE, to='sisponto.sector', verbose_name='Setor')),
                ('unit', smart_selects.db_fields.ChainedForeignKey(chained_field='company', chained_model_field='company', on_delete=django.db.models.deletion.CASCADE, to='sisponto.unit', verbose_name='Unidade')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisponto.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['person'],
            },
        ),
    ]
